name: CI
on: [push, pull_request]
jobs:
  test:
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
      - run: env
      - run: cat $GITHUB_EVENT_PATH
      - run: npm install
      - run: node index.js
